#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
latex: false
r_check_args: --as-cran

r_github_packages:
  - pneuvial/c3co.data
  - veseshan/pctGCdata
  - mskcc/facets
  
matrix:
  include:
#    - os: linux
#      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
      env:
        - R_KEEP_PKG_SOURCE=yes
        - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
        - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
        - _R_CHECK_CONNECTIONS_LEFT_OPEN_=true
        - _R_CHECK_LENGTH_1_CONDITION_=true
        - _R_CHECK_LENGTH_1_LOGIC2_=true
        - _R_CLASS_MATRIX_ARRAY_=true
    - os: linux
      r: devel
      env:
        - _R_RNG_VERSION_=3.5.2
#    - os: osx
#      r: oldrel
    - os: osx
      r: release
    - os: linux
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      r_packages:
        - covr
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label

bioc_packages:
  - BiocStyle
  
before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - export _R_CHECK_TIMINGS_=0  ## Report on timing for all tests
  
notifications:
  email:
    on_success: change
    on_failure: change
