#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
latex: false
r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual --as-cran
## env: MC_CORES=1  ## Disable parallel processing

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      r_github_packages:
      - jimhester/covr
      after_success:
      - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release

bioc_packages:
  - BiocInstaller
  - BiocStyle
  
repos:
  Rforge: http://R-Forge.R-project.org

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - export _R_CHECK_TIMINGS_=0  ## Report on timing for all tests
  
notifications:
  email:
    on_success: change
    on_failure: change
