---
title: "c3co from Segmented Data"
author: "Morgane Pierre-Jean, Julien Chiquet, Henrik Bengtsson and Pierre Neuvial"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{c3co from Segmented Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette aims to help users to run c3co on segmented data. 

This example is based on segmented data from [GSE47077] data sets. This data set is in the [c3co.data] package. It is also possible to use c3co algorithm from an RDS file containing segmentation.

Note that the file or the data must be a list with elements as follows
```{r}
data("segDat", package = "c3co.data")
names(segDat)
```

```{r}
str(segDat)
```

```{r, eval=FALSE}
library("c3co")
lambda.grid <- 10^-(3:5) ## penalty
K.list <- 2:5 ## candidate number of subclones
parameters.grid <- list(lambda = lambda.grid, nb.arch = K.list)
resc3co <- c3co(NULL, segDat = segDat, parameters.grid = parameters.grid)
```

[c3co.data]: https://github.com/pneuvial/c3co.data
[GSE47077]: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE47077
