---
title: "How to use c3co with PSCBS data"
author: "Morgane Pierre-Jean and Pierre Neuvial"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
---

## Introduction

This document provides a brief tutorial on using the c3co package from PSCBS data.

```{r}

library(c3co)
```

## Using wrapper
In this document we use the data from \code{facets} package.
\code{Facetswrapper} function segments and saves data from \code{facets} format to c3co format.
```{r}
pathPSCBS <- system.file("extdata",package="c3co.data")
stopifnot(pathPSCBS!="")
output.dir <- R.utils::Arguments$getWritablePath("outputPSCBS")
PSCBSwrapper(pathPSCBS,output.dir=output.dir, stat="C1C2")
```

## Run c3co ##
Now, you can run c3co by using this line:
```{r, eval=TRUE, message=FALSE}
resc3co <- c3co(NULL, nb.arch=2:4,output.dir=output.dir)
```
```{r, fig.width=7, fig.height=5}
Wplot(resc3co[[2]])
```
```{r, fig.width=7, fig.height=5}
dataBest <- resc3co[[2]]
dat <- loadPSCBSdata(pathPSCBS)
minMaxPos <- do.call(rbind, lapply(1:2, function(chromosome){
  print(chromosome)
  df <- dat[[1]]
  df$chr <- as.numeric(df$chr)
  idx <- which(df$chr==chromosome)
  df.sub <- df[idx,]
  print(str(df.sub))
  pos <- df.sub$pos
  return(list(chr=chromosome, minPos=min(pos), maxPos=max(pos)))
}))

df.CHR <- createZdf(minMaxPos, dataBest, chromosomes=c(1, 2), var="TCN")
df.CHRC1 <- createZdf(minMaxPos, dataBest, chromosomes=c(1, 2), var="Minor")
df.CHRC2 <- createZdf(minMaxPos, dataBest, chromosomes=c(1, 2), var="Major")
Zplot(df.CHR, ylab="TCN")
Zplot(df.CHRC1, ylab="C1", ylim=c(0,2))
Zplot(df.CHRC2, ylab="C2", ylim=c(0,4))
```

