#' Build several subclones
#'
#' @param len The number of probes in subclones.
#' @param dataAnnotTP A data frame containing the data used for the resampling. Need the total copy number in tumor \code{c}, \code{b} the B allele fraction in tumor, the type of alteration in \code{region} and the genotype in reference \code{genotype}
#' @param dataAnnotN A data frame containing the data used for the resampling. Need the total copy number in normal \code{c}, \code{b} the B allele fraction in normal, the type of alteration in \code{region} and the genotype in reference \code{genotype}
#' @param nbClones The number of subclones
#' @param bkps A list of breakpoints for each subclone
#' @param regions A list of altered regions for each subclone
#' @return A list of locus-level data for each subclone
#' @details The subclones are designed to mimic intra-tumor heterogeneity. In particular, all of the subclones generated by a single call to \code{buildSubclones} share the same germline genotypes. Their relative frequency corresponds to that of the input data.
#' @examples
#' dataAnnotTP <- acnr::loadCnRegionData(dataSet="GSE11976", tumorFrac=1)
#' dataAnnotN <- acnr::loadCnRegionData(dataSet="GSE11976", tumorFrac=0)
#' len <- 500*10
#' nbClones <- 2
#' bkps <- list(c(100,250)*10, c(150,400)*10)
#' regions <-list(c("(0,3)", "(0,2)","(1,2)"), c("(1,1)", "(0,1)","(1,1)"))
#' datSubClone <- buildSubclones(len, dataAnnotTP, dataAnnotN, nbClones, bkps, regions)
#' 
#' dataAnnotTP <- acnr::loadCnRegionData(dataSet="GSE13372", tumorFrac=1)
#' dataAnnotN <- acnr::loadCnRegionData(dataSet="GSE13372", tumorFrac=0)
#' len <- 500*10
#' nbClones <- 2
#' bkps <- list(c(100,250)*10, c(150,400)*10)
#' regions <-list(c("(0,1)", "(0,2)","(1,2)"), c("(1,1)", "(0,1)","(1,1)"))
#' datSubClone <- buildSubclones(len, dataAnnotTP, dataAnnotN,  nbClones, bkps, regions)
#' @export
buildSubclones <- function(len, dataAnnotTP, dataAnnotN, nbClones, bkps=list(), regions=list()){
    if (nbClones != length(regions)){ 
        stop("Argument 'nbClones' should match 'length(regions)'")
    }
    if(nbClones!=length(bkps)){ 
        stop("Argument 'nbClones' should match 'length(bkp)'")
    }
    if (is.factor(dataAnnotTP$region)){
        dataAnnotTP$region <- as.character(dataAnnotTP$region)
    }
    genotype <- NULL; rm(genotype);
    if (is.factor(dataAnnotTP$genotype)){
        dataAnnotTP$genotype <- as.character(dataAnnotTP$genotype)
    }
    
    tbl <- table(dataAnnotN$genotype)
    pct <- tbl/sum(tbl)
    genos <- sample(c(0, 0.5, 1), size=len, prob=pct, replace=TRUE)
    
    idxAA <- which(genos==0)
    idxAB <- which(genos==0.5)
    idxBB <- which(genos==1)
    pos <- c(idxAB, idxAA, idxBB)
    
    keepCols <- c("c", "b", "genotype", "region")
    dataAnnot <- data.frame(dataAnnotTP[, keepCols],
                            dataAnnotN[, c("c","b")])
    colnames(dataAnnot) <- c("ct", "baft", "genotype", "region", "cn", "bafn")
    
    datAA <- subset(dataAnnot,genotype==0)
    datAB <- subset(dataAnnot,genotype==0.5)
    datBB <- subset(dataAnnot,genotype==1)

    subClone <- lapply(1:nbClones, function(ii){
        bkp <- bkps[[ii]]
        reg <- regions[[ii]]
        
        bkpsAB <- sapply(bkp, function(bb) max(which(idxAB<=bb)))
        sim <- jointseg::getCopyNumberDataByResampling(length=length(idxAB), regData=datAB, bkp=bkpsAB, regions=reg)
        ssAB <- sim$profile
        
        bkpsAA <- sapply(bkp,function(bb) max(which(idxAA<=bb)))
        sim <- jointseg::getCopyNumberDataByResampling(length=length(idxAA), regData=datAA, bkp=bkpsAA, regions=reg)
        ssAA <- sim$profile
        
        bkpsBB <- sapply(bkp,function(bb) max(which(idxBB<=bb)))
        sim <- jointseg::getCopyNumberDataByResampling(length=length(idxBB), regData=datBB, bkp=bkpsBB, regions=reg)
        ssBB <- sim$profile
        
        ss <- rbind(ssAB, ssAA,ssBB)
        ss$pos <- pos
        o <- order(pos)
        ss[o, ]
    })
    return(subClone)
}

